[package]
name = "unity_extract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.41"
flate2 = "1.0.31"
clap = { version = "4.5.16", features = ["derive"] }
